### ISSUE TITLE
Error occurs when run `npm install gulp-xslt`

### ISSUE THREAD

**Issue by mixj93** [vecmezoni/gulp-xslt#7]
Environment
```
Operating system: macOS High Sierra
Node.js version: 8.9.4
npm version: 5.7.1
```
![image](https://user-images.githubusercontent.com/12998118/38185658-d09e506c-3681-11e8-9ad2-454f885adb85.png)

**Comment by vecmezoni** [comment]
@mixj93 I see that for some reason your node uses node-gyp v3.6.2 instead of v8.9.4. That's what probably causes the issue. Are you reinstalling from the scratch? 

Try to remove `node_modules` folder and reinstall again. If it won't help try to find out why npm is using older version of `node-gyp` then `node`.

**Comment by mixj93** [comment]
@vecmezoni it seems the latest version of node-gyp is v3.6.2 https://www.npmjs.com/package/node-gyp

**Comment by mixj93** [comment]
@vecmezoni I solved it. My python version is 3.x.x, 2.7 is fine.
